import { createHash, timingSafeEqual } from 'node:crypto'
import { env } from '@/lib/env'
import {
  TUS_CHUNK_BYTES,
  type AssetStatus,
  type PlaybackTicket,
  type UploadTicket,
  type Usage,
  type VideoProvider,
} from './provider'

/**
 * A deterministic, network-free `VideoProvider`.
 *
 * Not a mock bolted onto the tests — a first-class driver (`VIDEO_DRIVER=fake`) so that CI, the
 * Playwright suite, and a planner demo on venue wifi all exercise the same code paths as
 * production without a Bunny account. Playback resolves to a bundled sample HLS stream, so
 * "press play and something plays" is verifiable end to end offline.
 */
export class FakeVideoProvider implements VideoProvider {
  readonly name = 'fake'

  /** Assets transition uploading → processing → ready on a timer, mimicking a transcode. */
  private readonly assets = new Map<string, { createdAt: number; durationS: number; sizeBytes: number }>()

  private static readonly PROCESSING_MS = 1_500

  /** Generated by `scripts/make-sample-video.mjs`. Our own bytes, no licence question. */
  static readonly SAMPLE_CLIP = '/media/sample.webm'
  /**
   * Generated by `scripts/make-sample-hls.mjs` (N-90). A real HLS manifest over real fMP4
   * segments — not `SAMPLE_CLIP` — because `useHlsPlayback.ts`'s `isManifest` check is what
   * decides whether a URL goes through `hls.js`/`MediaSource`/`blob:` at all, and a `.webm`
   * never did. That gap is what let a broken CSP directive reach production behind an all-green
   * suite on 18 September 2026.
   */
  static readonly SAMPLE_MANIFEST = '/media/hls/playlist.m3u8'

  async createUpload({ title, sizeBytes }: { title: string; sizeBytes: number }): Promise<UploadTicket> {
    const providerId = `fake_${createHash('sha1').update(`${title}:${sizeBytes}:${Date.now()}`).digest('hex').slice(0, 20)}`
    this.assets.set(providerId, {
      createdAt: Date.now(),
      // A stable pseudo-duration between 45s and 20min, derived from the id so it survives a
      // reload without any storage.
      durationS: 45 + (parseInt(providerId.slice(-4), 16) % 1155),
      sizeBytes,
    })
    return {
      providerId,
      tusEndpoint: '/api/dev/tus',
      headers: { VideoId: providerId, LibraryId: 'fake' },
      chunkSizeBytes: TUS_CHUNK_BYTES,
    }
  }

  async getPlaybackToken({
    providerId,
    scope,
    ttlS,
  }: {
    providerId: string
    scope: { catalogueId: string; titleId: string }
    ttlS: number
  }): Promise<PlaybackTicket> {
    const expires = Math.floor(Date.now() / 1000) + ttlS
    // Signed exactly like the real thing, so the scoping test (doc 10 §1 test 7) is meaningful
    // against this driver too.
    const token = createHash('sha256')
      .update(`${env.SESSION_SECRET}:${providerId}:${scope.catalogueId}:${scope.titleId}:${expires}`)
      .digest('base64url')

    return {
      // A real HLS manifest, not an ABR ladder — standing up several renditions would be
      // theatre, exercising our own fixture server rather than Bunny. One rendition is enough to
      // send every guest and every test through `hls.js`, `MediaSource` and `blob:` for real
      // (N-90), which is what E2E-1's "playback starts and resumes at a real position" assertion
      // needs to actually be testing. The token is still signed exactly as the real driver signs
      // it, so the scoping test (doc 10 §1 test 7) stays meaningful.
      playbackUrl: `${FakeVideoProvider.SAMPLE_MANIFEST}?token=${token}&expires=${expires}`,
      thumbnailsUrl: null,
      expiresAt: new Date(expires * 1000).toISOString(),
    }
  }

  async getStatus(providerId: string): Promise<AssetStatus> {
    const asset = this.assets.get(providerId)
    if (!asset) {
      // Seeded demo content has no in-process record; treat it as long since ready.
      return {
        state: 'ready',
        durationS: null,
        storageBytes: null,
        posterCandidates: [],
        thumbnailsUrl: null,
        errorMessage: null,
      }
    }

    const ready = Date.now() - asset.createdAt > FakeVideoProvider.PROCESSING_MS
    return {
      state: ready ? 'ready' : 'processing',
      durationS: ready ? asset.durationS : null,
      /**
       * The encoded ladder is bigger than the file that was sent. 1.4x is a plausible stand-in so
       * the storage cap is exercised by the suite rather than only in production.
       */
      storageBytes: ready ? Math.round(asset.sizeBytes * 1.4) : null,
      posterCandidates: ready ? [1, 2, 3].map((n) => `frame-${n}`) : [],
      thumbnailsUrl: null,
      errorMessage: null,
    }
  }

  async getAssetUrl({
    providerId,
    file,
  }: {
    providerId: string
    file: string
    ttlS: number
  }): Promise<string> {
    // Deterministic generated artwork, so an offline demo shows three distinguishable frames.
    return `/api/poster/frame?asset=${encodeURIComponent(providerId)}&n=${encodeURIComponent(file)}`
  }

  async getDownloadUrl({ providerId }: { providerId: string; ttlS: number }) {
    return { url: `/media/sample.webm?download=${providerId}`, label: 'original' }
  }

  async deleteAsset(providerId: string): Promise<void> {
    this.assets.delete(providerId)
  }

  async getUsage(): Promise<Usage> {
    return { storedGb: 0, watchSeconds: 0, deliveredGb: 0 }
  }

  verifyWebhook(rawBody: string, headers: Headers) {
    const provided = headers.get('x-bunnystream-signature') ?? headers.get('x-bunny-signature') ?? ''
    const expected = createHash('sha256').update(`${env.SESSION_SECRET}${rawBody}`).digest('hex')
    const a = Buffer.from(provided)
    const b = Buffer.from(expected)
    if (a.length !== b.length || !timingSafeEqual(a, b)) return null

    try {
      const payload = JSON.parse(rawBody) as { VideoGuid?: string }
      return payload.VideoGuid ? { providerId: payload.VideoGuid } : null
    } catch {
      return null
    }
  }
}
