#!/usr/bin/env tsx
/**
 * Produce a single paste-ready SQL script for a brand-new Supabase project.
 *
 * Why generate rather than execute: applying DDL needs the database password or a linked
 * Supabase CLI, and the service-role key alone cannot run arbitrary SQL over PostgREST. Rather
 * than inventing an `exec_sql` RPC — which would be a permanent remote-code-execution hole in
 * a database holding people's weddings — this prints the script and you paste it into the SQL
 * editor once. It is a thirty-second manual step that removes a standing risk.
 *
 *   pnpm bootstrap:sql > /tmp/bootstrap.sql
 *
 * Then: Supabase dashboard → SQL Editor → paste → Run.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { hashSecret } from '../lib/crypto'

const migrationsDir = join(process.cwd(), 'supabase/migrations')
const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort()

const orgId = randomUUID()
const operatorEmail = process.env.SEED_OPERATOR_EMAIL ?? 'operator@mehfilbox.test'
const operatorPassword = process.env.SEED_OPERATOR_PASSWORD ?? 'local-demo-password'
const orgName = process.env.SEED_ORG_NAME ?? 'Kalyanam Weddings'

const out: string[] = [
  '-- ═══════════════════════════════════════════════════════════════════════════',
  '-- Mehfilbox — one-time bootstrap for a new Supabase project.',
  '-- Generated by `pnpm bootstrap:sql`. Safe to run once, on an empty project.',
  '-- ═══════════════════════════════════════════════════════════════════════════',
  '',
  'begin;',
  '',
]

for (const file of files) {
  out.push(`-- ── ${file} ${'─'.repeat(Math.max(0, 66 - file.length))}`)
  out.push(readFileSync(join(migrationsDir, file), 'utf8').trim())
  out.push('')
}

out.push(
  '-- ── First org ───────────────────────────────────────────────────────────────',
  `insert into orgs (id, name, slug, branding)`,
  `values ('${orgId}', ${quote(orgName)}, 'kalyanam', '{"accent":"#d11a2a","presentedBy":${JSON.stringify(orgName)}}'::jsonb)`,
  'on conflict (slug) do nothing;',
  '',
  'commit;',
  '',
  '-- ── The first operator ──────────────────────────────────────────────────────',
  '--',
  '-- `operators.id` references `auth.users(id)`, so the account has to exist in Supabase Auth',
  '-- first. Create it in the dashboard (Authentication → Users → Add user), then run:',
  '--',
  `--   insert into operators (id, org_id, email, name, role, password_hash)`,
  `--   values ('<auth.users.id>', '${orgId}', ${quote(operatorEmail)}, 'Operator', 'admin',`,
  `--           ${quote(hashSecret(operatorPassword))});`,
  '--',
  '-- The password_hash column is only read when the app verifies credentials itself rather',
  '-- than through Supabase Auth (see lib/admin/session.ts). The hash above is for',
  `-- "${operatorPassword}" — change it before anything real.`,
)

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

console.log(out.join('\n'))
